const LANGUAGE = 'javascript';

// START TOKENS
const START_CODE_MARKDOWN_TOKEN = `\`\`\`${LANGUAGE}`;
const END_CODE_MARKDOWN_TOKEN = '```';
// END TOKENS

const REPL_IT_ROOT = 'https://repl.it';

module.exports = {
  START_CODE_MARKDOWN_TOKEN,
  END_CODE_MARKDOWN_TOKEN,
  REPL_IT_ROOT,
  MARKDOWN_METADATA_DELIMITER: '---'
};
